title: "Site"

tabs:
  content:
    label: "Inhalt"
    icon: document
    sections:
      pages:
        label: "Seiten"
        type: "pages"

  settings:
    label: "Allg. Einstellungen"
    icon: cog
    columns:
      - width: "1/2"
        sections:
          infoTimes:
            type: "fields"
            fields:
              marqueeHeadline:
                type: "headline"
                label: "Info-Banner"

              marqueeEnabled:
                label: "Info-Banner: Anzeige"
                type: "toggle"
                default: false

              marqueeText:
                label: "Info-Banner: Text"
                type: "textarea"
                size: "small"
                buttons: true
                placeholder: "News, Betriebsferien, etc."
                when:
                  marqueeEnabled: true

              openingHoursHeadline:
                type: "headline"
                label: "Öffnungszeiten"

              # FIXED DAYS (Mo–So) — no structure, no reordering, no adding/removing rows
              monClosed:
                label: "Montag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              monTimes:
                label: "Montag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  monClosed: false

              monNote:
                label: "Montag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  monClosed: false

              tueClosed:
                label: "Dienstag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              tueTimes:
                label: "Dienstag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  tueClosed: false

              tueNote:
                label: "Dienstag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  tueClosed: false

              wedClosed:
                label: "Mittwoch: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              wedTimes:
                label: "Mittwoch: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  wedClosed: false

              wedNote:
                label: "Mittwoch: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  wedClosed: false

              thuClosed:
                label: "Donnerstag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              thuTimes:
                label: "Donnerstag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  thuClosed: false

              thuNote:
                label: "Donnerstag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  thuClosed: false

              friClosed:
                label: "Freitag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              friTimes:
                label: "Freitag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  friClosed: false

              friNote:
                label: "Freitag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  friClosed: false

              satClosed:
                label: "Samstag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              satTimes:
                label: "Samstag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  satClosed: false

              satNote:
                label: "Samstag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  satClosed: false

              sunClosed:
                label: "Sonntag: geschlossen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false
                width: "1/4"

              sunTimes:
                label: "Sonntag: Zeiten"
                type: "text"
                placeholder: "11:30–14:00, 17:30–22:00"
                width: "3/4"
                when:
                  sunClosed: false

              sunNote:
                label: "Sonntag: Hinweis"
                type: "text"
                placeholder: "z.B. Küche bis 21:30"
                when:
                  sunClosed: false

              specialOpeningHours:
                label: "Sonderöffnungszeiten"
                type: "structure"
                help: "Feiertage, Ferien, Events etc. (Datum überschreibt nicht automatisch – nur als Zusatzanzeige)"
                columns:
                  date:
                    width: "1/3"
                  times:
                    width: "2/3"
                fields:
                  date:
                    label: "Datum"
                    type: "date"
                    display: "DD.MM.YYYY"
                    required: true
                  closed:
                    label: "Geschlossen"
                    type: "toggle"
                    text: ["Nein", "Ja"]
                    default: false
                  times:
                    label: "Zeiten"
                    type: "text"
                    placeholder: "11:30–14:00, 17:30–22:00"
                    when:
                      closed: false
                  note:
                    label: "Hinweis"
                    type: "text"
                    placeholder: "Küche bis 21:30 / nur abends geöffnet"

              holidayEnabled:
                label: "Betriebsferien anzeigen"
                type: "toggle"
                text: ["Nein", "Ja"]
                default: false

              holidayFrom:
                label: "Von"
                type: "date"
                display: "DD.MM.YYYY"
                width: "1/2"
                when:
                  holidayEnabled: true

              holidayTo:
                label: "Bis"
                type: "date"
                display: "DD.MM.YYYY"
                width: "1/2"
                when:
                  holidayEnabled: true

              holidayNote:
                label: "Hinweis"
                type: "text"
                placeholder: "Wir sind ab dem 07.01. wieder für Sie da."
                when:
                  holidayEnabled: true

      - width: "1/2"
        sections:
          addressContact:
            type: "fields"
            fields:
              addressHeadline:
                type: "headline"
                label: "Adresse"

              addressName:
                label: "Name"
                type: "text"
                default: "Ristorante La Rotonda"

              addressStreet:
                label: "Strasse / Nr."
                type: "text"

              addressZipCity:
                label: "PLZ / Ort"
                type: "text"
                default: "8134 Adliswil"

              addressPhone:
                label: "Telefon"
                type: "text"
                placeholder: "+41 44 123 45 67"
                width: "1/2"

              addressEmail:
                label: "E-Mail"
                type: "email"
                width: "1/2"
              
          cursorSettings:
            type: fields
            fields:
              cursorSettingsHeadline:
                type: headline
                label: "Cursor-Effekte"
              enablePizzaCursor:
                label: "Pizza-Cursor aktivieren"
                type: toggle
                default: false
                width: 1/2
              enableCrumbTrail:
                label: "Crumb-Trail aktivieren"
                type: toggle
                default: false
                width: 1/2
              cursorColor:
                label: "Cursor-Farbe"
                type: color
                default: "#C5B358"
                width: 1/2
              crumbColor:
                label: "Crumb-Farbe"
                type: color
                default: "#C5B358"
                width: 1/2
  seo: seo/page
